#!/bin/sh

# Set wallpaper with nitrogen
nitrogen --restore &

# Start compositor
picom &

# Bind keys
sxhkd &

# Set keyboard settings (custom script)
setkeyboard &

# Start statusbar
polybarstart &

# Start window manager
bspwm
