#!/bin/sh
# Set wallpaper with nitrogen
nitrogen --restore &

# Add dual keyboard layouts with setxkbmap
setxkbmap -option 'grp:alt_space_toggle' -layout us,no -option nodeadkeys &

# Start statusbar
polybarstart &

# Start window manager
i3
