#!/bin/sh
# Set wallpaper with nitrogen
nitrogen --restore &

# Start compositor
picom &

# Bind keys
sxhkd &

# Add dual keyboard layouts with setxkbmap
setlayout &

# Start statusbar
polybarstart &

# Start window manager
bspwm
