[directory]
style = "bold blue"
truncation_length = -1
truncate_to_repo = false

[character]
success_symbol = "[❯](bold yellow)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold blue)"

[custom.nova]
command = "echo \"$PROJECTNAME\""
when = "test -n \"$PROJECTNAME\""
format = "configured [$output]($style) "
style = "bold green"

[status]
disabled = false
