#!/bin/sh

# Assigning desktops to specific monitors
if [ $(xrandr | grep " connected" | wc -l) -gt 1 ]; then
    bspc monitor eDP-1 -d 2 4 6 8
    bspc monitor DP-3-3 -d 1 3 5 7 9
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

# Assigning programs to specific desktops (mostly for work)
bspc rule -a novaCWP desktop=1
bspc rule -a multiProcessStarter desktop=4
bspc rule -a discord desktop=4
bspc rule -a mps-terminal desktop=5

# Use grid layout on desktop 5 (all mps-terminals go here)
bsp-layout set grid 5

# Theming
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#282828"
bspc config active_border_color "#282828"
bspc config focused_border_color "#e1b655"

bspc config focus_follows_pointer true

# Daemonize process that moves mouse when changing window focus
focus-and-center &

# Use normal cursor when cursor is not over a window
xsetroot -cursor_name left_ptr
